import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ApolloWrapper } from './ApolloWrapper'
import TigerSVG from './components/svg/Tigersvg'
import Nav from './components/nav/Nav'
const inter = Inter({ subsets: ['latin'] })

import authToken from './actions/token'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Nav />
        {children}

        {/* <TigerSVG /> */}
      </body>
    </html>
  )
}
